# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: The Caretaker Model (of open software project management)
email: felix@passcod.name

version: "0.1"
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.

baseurl: ""
url: "https://caretaker.passcod.name"
twitter_username: passcod
github_username: passcod

range_range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
