# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: The Caretaker Model (of open software project management)
email: felix@passcod.name

version: "0.1"
description: ""
seo_description: >-
    An open software management model aimed at changing the expectations on
    and from developers, contributors, helpers, and users, in the goal of
    redistributing burden and effort more fairly, for small to medium projects.

baseurl: ""
url: "https://caretaker.passcod.name"
date_format: "%b %-d, %Y"

range_range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
