# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: The Caretaker Model (of open software project management)
email: felix@passcod.name

version: "0.1"
description: ""
seo_description: >-
    A open software contribution model that redistributes work more fairly,
    operates at higher trust, and allows projects to survive and grow even
    if a creator or team is away, with very little effort required on their part.

baseurl: ""
url: "https://caretaker.passcod.name"
date_format: "%b %-d, %Y"

range_range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
