# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: The Caretaker System (for open software projects)
email: felix@passcod.name

version: "0.1"
description: ""
seo_description: >-
    A “contribution system addon” for open software projects to ease maintainer burden and encourage
    contributions even at low activity levels.

baseurl: ""
url: "https://caretaker.passcod.name"
date_format: "%b %-d, %Y"

range_range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
